apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /pod1
          backend:
            serviceName: nginx-pod1
            servicePort: 90
        - path: /pod2
          backend:
            serviceName: service-pod2
            servicePort: 100

            # the ingress resouce wont work until and unless you have ingress controller 
            # I have installed ingress controller using the helm package controller 

            # helm install nginx stable/nginx-ingress
            # helm repo update 